### ISSUE TITLE
App crash when registering USB stick when password field remains empty

### ISSUE THREAD

**Issue by wright-david** [pazaan/640gAndroidUploader#1]
Code version: commit 4c42c64 (master)
Environment:   AVD Nexus_5X_API_21 [emulator-5554]

SIGSEGV when registering USB stick when password field remains empty

[Crash log](https://gist.github.com/wright-david/b513bb94d3fdccb7adf013333138cb66)

**Comment by pazaan** [comment]
Do you have any more STR's around this? Whenever I try to register with an empty password field, it tells me that the Username or password is incorrect.

**Comment by pazaan** [comment]
Added a requirement to have a non-empty password, even though I couldn't repro. @wright-david, are you able to tell me if this is still an open issue?

**Comment by wright-david** [comment]
Using Pre-release v0.1.0  (#1) on the Android emulator still gave a crash with password of single digit (numeric) - which on an earlier commit I also saw on a real device.

However same tricks using Pre-release v0.1.0  (#2) on a real phone don't crash it any more.

Your call :)

**Comment by pazaan** [comment]
Made a password mandatory. Any crashes in the login window show be something else now.
