### ISSUE TITLE
Pump time offset and Polling

### ISSUE THREAD

**Issue by Pogman** [pazaan/640gAndroidUploader#100]
From master branch:

MainActivity.java    line 656

```
long nextPoll = pumpStatusData.getEventDate().getTime() + pumpStatusData.getPumpTimeOffset()
+ MedtronicCnlIntentService.POLL_GRACE_PERIOD_MS + MedtronicCnlIntentService.POLL_PERIOD_MS;

```
The pump time offset must be subtracted from the event time and not added.

This should be:

```
long nextPoll = pumpStatusData.getEventDate().getTime() - pumpStatusData.getPumpTimeOffset()
+ MedtronicCnlIntentService.POLL_GRACE_PERIOD_MS + MedtronicCnlIntentService.POLL_PERIOD_MS;
```

PumpStatusEvent.java   line 42

```
@Ignore
private long pumpTimeOffset; // millis the pump is ahead
```

The @Ignore is making the offset always be zero and needs to be removed.

As it stands in the branch the next poll time will always be event time + 5 mins 30 secs (or whatever has been set for these)

This means that the time offset from pump to uploader is not being accounted for. The noted changes will fix that.

**Comment by volkerrichert** [comment]
i'm digging into that right now.. :-)

Are you sure? There is an error, i found a few secs ago. It's pooling to often. but if i sub the offset (which i added before to correct Date), it'll will be even more often

see
`
pumpRecord.setEventDate(new Date(sgvDate.getTime() - pumpRecord.getPumpTimeOffset()));
`

**Comment by Pogman** [comment]
Absolutely sure for this (for now ;) )  There is some other problems related to polling for sure and I think there may be multiple intents running and something somewhere is not been cancelled

**Comment by volkerrichert** [comment]
i'll try to find.

**Comment by Pogman** [comment]
Ok I'll take back my "sure" and I'll look further to be sure to be sure

**Comment by Pogman** [comment]
Yeah I see that code - pitfalls and traps my friend arrrg

**Comment by volkerrichert** [comment]
ok, some detail...

`
01-09 20:42:13.415 14484-14484/info.nightscout.android D/MedtronicCnlAlarmReceiver: Received broadcast message at Mon Jan 09 20:42:13 GMT+01:00 2017
01-09 20:42:13.465 14484-14484/info.nightscout.android D/MedtronicCnlAlarmManager: try to set Alarm at Mon Jan 09 20:47:43 GMT+01:00 2017
01-09 20:42:13.468 14484-14484/info.nightscout.android D/MedtronicCnlAlarmManager: Alarm set to fire at Mon Jan 09 20:47:43 GMT+01:00 2017
[...]
01-09 20:42:21.692 14484-14895/info.nightscout.android D/MedtronicCnlReader: Finished getPumpTime with date Mon Jan 09 20:43:38 GMT+01:00 2017
01-09 20:42:21.692 14484-14895/info.nightscout.android D/MedtronicCnlIntentService: Time offset between pump and device: 76308 millis.
[...]
01-09 20:42:21.920 14484-14895/info.nightscout.android D/PumpStatusResponseMessage: original sgv date: Mon Jan 09 20:39:12 GMT+01:00 2017
[...]
01-09 20:42:21.995 14484-14484/info.nightscout.android D/MedtronicCnlAlarmManager: try to set Alarm at Mon Jan 09 20:38:24 GMT+01:00 2017
01-09 20:42:21.996 14484-14484/info.nightscout.android D/MedtronicCnlAlarmManager: Alarm set to fire at Mon Jan 09 20:42:21 GMT+01:00 2017
`

but the "try to set Alarm" is wrong.... So, there is a bug. but a different one

**Comment by volkerrichert** [comment]
BTW, this is output from develop branch. ;-)

**Comment by Pogman** [comment]
Closing this for now as while the OP issue is true the code counters it elsewhere and the next poll time as set is correct.

volker noted it here:

pumpRecord.setEventDate(new Date(sgvDate.getTime() - pumpRecord.getPumpTimeOffset()));
