### ISSUE TITLE
Use Retrofit for upload REST API

### ISSUE THREAD

**Issue by jgwashburn** [pazaan/640gAndroidUploader#103]
Use http://square.github.io/retrofit/ to build the http request for the upload to the Nightscout web site.

Existing Code ref: 
https://github.com/pazaan/640gAndroidUploader/blob/63e1bdb8cfda52d172a6dcca9254a4fb6ad8a204/app/src/main/java/info/nightscout/android/upload/nightscout/NightscoutUploadIntentService.java#L139

Value:
 * type safety 
 * easier s/w development going forward.

**Comment by jgwashburn** [comment]
* retrofit - based Nightscout API 
https://github.com/jgwashburn/640gAndroidUploader/blob/retrofit/app/src/main/java/info/nightscout/api/UploadApi.java

* Usage 
https://github.com/jgwashburn/640gAndroidUploader/blob/retrofit/app/src/main/java/info/nightscout/android/upload/nightscout/NightScoutUpload.java

Next: test framework development, testing, instrumentation

**Comment by pazaan** [comment]
Thanks @jgwashburn. Can you please make a PR against the develop branch?

**Comment by jgwashburn** [comment]
Sure . Just need to do a bit more testing . But looking good so far in unit tests.

**Comment by pazaan** [comment]
Feel free to check in unit tests as well :)
`develop` is pretty safe. We regress heavily before merging to master.

**Comment by jgwashburn** [comment]
merged into develop branch. Thanks @pazaan and @volkerrichert for the collab.
