### ISSUE TITLE
Refuses to build from bugfender

### ISSUE THREAD

**Issue by drbanting** [pazaan/640gAndroidUploader#110]
Trying to build this in Android studio and get bugfender errors when trying to build it (MacOS Sierra)
> app/bugfender.properties (No such file or directory)
Never used bugfender, is there any way around using it?

**Comment by volkerrichert** [comment]
yes, register to bugfender and create that file.

see https://github.com/pazaan/640gAndroidUploader/blob/b4fab7248c660d2eb89d5fe475c3482f2d7b2189/README.md#development---getting-started
