### ISSUE TITLE
Automate the release mechanism to update the build version

### ISSUE THREAD

**Issue by wright-david** [pazaan/640gAndroidUploader#15]
Code version: Pre-release v0.1.1  commit bf69577

App version in Preferences is still listed as 0.1.0, also in Android's Settings>App info

Need to add some mechanism to auto-update both of these from build version.

**Comment by pazaan** [comment]
See:
https://developer.android.com/studio/publish/versioning.html
https://developer.android.com/studio/build/build-variants.html
https://github.com/researchgate/gradle-release

Make sure to update `android:versionCode` as well as `android:versionName`
