### ISSUE TITLE
Menu button not showing for some people

### ISSUE THREAD

**Issue by pazaan** [pazaan/640gAndroidUploader#25]
Some folks on the Nightscout for Medtronic FB group didn't see a menu icon in the app.
They resolved it by [pressing and holding the context menu button to get the menu](
http://i-cdn.phonearena.com/images/articles/117867-thumb/Samsung-Galaxy-S5-hidden-menu-key.jpg).

We need to initially update the documentation to cover this, and ideally find the cause and fix it.

**Comment by wright-david** [comment]
I think this is already covered in the wiki: <https://github.com/pazaan/640gAndroidUploader/wiki/Getting-Started:-Installation>


"Note - depending on your Android device, 'Preferences' may be accessed either via an on-screen button (e.g. three dots in the action bar at the top of the screen, or elsewhere) **or your device may have a physical button** – usually the same button as settings"

They have posh phones ;)

![image](https://cloud.githubusercontent.com/assets/14233575/15436773/73dbd42e-1ebb-11e6-888d-a680f2236c22.png)

**Comment by pazaan** [comment]
Sounds good to me!
