### ISSUE TITLE
Synchronise polling timer to match CGM times

### ISSUE THREAD

**Issue by pazaan** [pazaan/640gAndroidUploader#28]
The timer for polling the pump is currently a fixed 5 minutes from when the app starts, or you press "Get Now".
It should dynamically synchronise against the last CGM time, so that you don't get things like "8 minutes ago" for a BGL, even though the pump was polled 3 minutes ago.

**Comment by LittleDMatt** [comment]
Ideallt, would you need to link this to a check on pump time accuracy? The 640g has a reputation for gaining time...

**Comment by pazaan** [comment]
@LittleDMatt I think that checking on pump time accuracy would be a separate ticket.

**Comment by LittleDMatt** [comment]
Will raise on new ticket Lennart as an enhancement - polling optimsation could be independent of pump time accuracy, just by looking at difference in reported pump and SG times

**Comment by Bal00** [comment]
I guess the ap should keep checking the pump-time phone-time offset to calculate next polling time and not remember it for too long (if at all)

**Comment by pazaan** [comment]
Polling offset changed to 1 minute past next expected CGM update in 0.3.0
