### ISSUE TITLE
Store values in local database

### ISSUE THREAD

**Issue by Bal00** [pazaan/640gAndroidUploader#29]
Currently ntermittent gaps occur in data stream if a scheduled upload fails. Implement one or two re-attempts if either pump comms or REST fails (can this be detected?). Compliments #28

**Comment by pazaan** [comment]
I'll expand this to make it a general feature request to store values in a local database. This will include uploading all values that are marked as not having been uploaded.

**Comment by Bal00** [comment]
A re-attempt would be nice, although backdated data will be really nice an definitely of value, knowing that if a sample is missed it's another 5 minute wait until any fresh data can come is frustrating..

**Comment by pazaan** [comment]
Added in 0.3.0
