### ISSUE TITLE
"Pump time" is displaying a time-stamp even though no pump is connected

### ISSUE THREAD

**Issue by wright-david** [pazaan/640gAndroidUploader#3]
Code version: commit 4c42c64 (master) 
Environment: Sony D2303 (Android 5.1.1, API 22) Xperia M2

After app launch "Pump time" is displaying a time-stamp even though no pump (nor CNL stick) is connected.This suggests it's picking up the Android device time.

It should display null/none for "Pump time" until it's actually received a time-stamp from the pump.

**Comment by pazaan** [comment]
This date is the "Pump time" at the time when the "BGL at" was taken (which is currently incorrect - it should be the last correct value. Currently if there's an error, it's the current Android time).
The question is - should "Pump time" be blank unless the *last* entry was successful?

**Comment by wright-david** [comment]
Do you need two different timestamps for one BG/SGV reading? Confusing.
IDK details of Nightscout website back end / database, or the uploader (sigh), but surely only one out of the uploader or the pump should be in charge of timestamps?

**Comment by Bal00** [comment]
Timestamps should be as "true" as possible, so should be the time of reading corrected for pump offset from phone time (assume phone is correct, distrust pump)...

**Comment by pazaan** [comment]
0.3.0 now shows results in "true" time instead of "pump time". We still need to add a warning or other notification that the pump is out of sync with real time.

**Comment by pazaan** [comment]
Closing this, since #45 covers the outstanding work.
