### ISSUE TITLE
WiFi Hack causes crash

### ISSUE THREAD

**Issue by Bal00** [pazaan/640gAndroidUploader#30]
For an unknown reason my rig has a lot of (DNS?) errors on REST. With the WiFi hack disabled this is generally stable, but with the WiFi hack enabled there are very frequent (often instant on start-up) crashes. 

Hardware: MotoG (3rd G?)

Typical_Medtronic640gUploader.log.txt shows normal operation for my rig over a day or so (pump is often out of range during the day but always in range at night). 

Wifi_Hack_Medtronic640gUploader.log.txt is downloaded an hour later when the WiFi hack was enabled at the start of the hour (around 17:30 on 20th May).

Let me know if you would like specific tests.

[Wifi_Hack_Medtronic640gUploader.log.txt](https://github.com/pazaan/640gAndroidUploader/files/275153/Wifi_Hack_Medtronic640gUploader.log.txt)
[Typical_Medtronic640gUploader.log.txt](https://github.com/pazaan/640gAndroidUploader/files/275154/Typical_Medtronic640gUploader.log.txt)

**Comment by pazaan** [comment]
The Wi-Fi hack is a remnant of starting with the MedtronicUploader code. I'd left it in there, though I'm not sure what its purpose is, and I've never tested it.

Do we even need it?
