### ISSUE TITLE
BGL or BG or SGV?

### ISSUE THREAD

**Issue by wright-david** [pazaan/640gAndroidUploader#31]
This may be a cultural thing...

"BGL" on the main display is causing some minor confusion as the more usual term in UK for blood glucose is just "BG".

However I guess terminology may vary between countries/regions.

Also should it be SGV if it's from the CGM and not BG?

**Comment by Bal00** [comment]
I agree that CGM should always be "S" (sensor) as it is measuring interstitial fluid glucose, not blood (and has associated delay and lag). "V" (value) is more common terminology in Nightscout circles than "L" (level) as far as I can tell. However I would say that @LittleDMatt would be our authoritative voice on this...

**Comment by pazaan** [comment]
Actually, that's a fair call. The pump itself displays it as `SG` (Sensor Glucose, I guess), and fingerstick entries as `BG`

**Comment by wright-david** [comment]
@pazaan  Note "BGL" also appears under settings: ".. enable upload of BGL data to Nighscout" 
- just remove "BGL"
