### ISSUE TITLE
Uploader not working when the phone sleep

### ISSUE THREAD

**Issue by zekeat09** [pazaan/640gAndroidUploader#32]
Uploader not working when the phone sleep. The uploader only work when set the phone "always on".
## Your Environment

- Uploader Version Number: 0.1.0
- Your Android Phone Model Name (e.g. Samsung J1 Ace): Asus-Z010D
- Android Version Number (e.g. use 4.4 for 4.4.4): 5.0.2
- Network Connection at the time the issue occurred (Wi-Fi, Mobile): wifi

**Comment by pazaan** [comment]
Note to self: https://developer.android.com/training/scheduling/wakelock.html

**Comment by wright-david** [comment]
@zekeat09   
Hi. If you'll forgive me using something borrowed from elsewhere:

- There are various settings on your Android device that will affect the uploader App - general power saving (Settings > Power Management), as well as settings related to Wi-Fi and mobile data.

- Note that these settings will vary between different Android versions and different devices, so you will need to research about your own device to find out what you need to do.

- It may be possible to add the uploader App to a list of exceptions, or to turn off those features entirely.

Can you check these out and let us know whether you still experience problems?

**Comment by zekeat09** [comment]
Hi,

I tried my best to find power management setting that cause problem to the Uploader apps, unfortunately not successful. The problem still remain. I gave up and change the phone to ZTE T620, it works well !

Again, thanks for your help.

Regards
Kent

Sent from my iPhone

On 21 May 2016, at 18:25, David Wright <notifications@github.com<mailto:notifications@github.com>> wrote:


@zekeat09<https://github.com/zekeat09>

Hi. If you'll forgive me using something borrowed from elsewhere:

  *   There are various settings on your Android device that will affect the uploader App - general power saving (Settings > Power Management), as well as settings related to Wi-Fi and mobile data.

  *   Note that these settings will vary between different Android versions and different devices, so you will need to research about your own device to find out what you need to do.

  *   It may be possible to add the uploader App to a list of exceptions, or to turn off those features entirely.

Can you check these out and let us know whether you still experience problems?

-

**Comment by pazaan** [comment]
0.3.0 uses background IntentServices and the AlarmManager to communicate with the pump now. Would be interested to hear if people are still having this problem in 0.3.0 (I never had it to begin with, so I can't test it).

**Comment by ltomovski** [comment]
Hi
I am using 0.4.0 ... it does not work on Lenovo K5 on 5.1.1 .. If I change the phone not to sleep the problem is gone
Note that 0.4.0 works just fine on Samsung Galaxy S6 Edge on 6.0.1 
As far as I know 6.0.1 introduce some new battery saving features ... not that on my S6 I have set NS to not save power (App power saving)

**Comment by volkerrichert** [comment]
is this still an issue with the 0.4.0 release?

**Comment by pazaan** [comment]
The feedback on your changes have been positive, so I think that we can close that out.
