### ISSUE TITLE
Initial USB stick registration flow is flaky

### ISSUE THREAD

**Issue by pazaan** [pazaan/640gAndroidUploader#39]
A very specific flow is required (ie, plug in USB first, launch app). There are also various scenarios where one needs to click "Get Now" to get some meaningful state.
This should be a very user-friendly and intuitive flow.

**Comment by wright-david** [comment]
"plug in USB first, launch app" - is that really necessary? 
App seems to have auto-registration (though see my comments in issue #5)

**Comment by pazaan** [comment]
It's a current requirement of existing janky code flow. This issue means to address that ;)

**Comment by pazaan** [comment]
Fixed in 0.3.0
