### ISSUE TITLE
Stick registration if account has never uploaded pump data to CareLink

### ISSUE THREAD

**Issue by pazaan** [pazaan/640gAndroidUploader#40]
Pablo has found that if you don't use a CareLink account to upload pump data to CareLink, that the stick login/registration process fails. Perhaps it's just that the serial has to be registered by CareLink at _some_ stage.

**Comment by wright-david** [comment]
Added info to wiki. Is there any other action to take on this?

**Comment by pazaan** [comment]
I'll see if there's anything I can do in code to detect this condition, so we can raise a separate error to username/password.

**Comment by wright-david** [comment]
Expanded info on wiki after another case

**Comment by pazaan** [comment]
Fixed by commit a323eb70b191510f6f954c6c252df16ed0e73acd
