### ISSUE TITLE
Device battery status arrives in pairs

### ISSUE THREAD

**Issue by wright-david** [pazaan/640gAndroidUploader#41]
Code version: commit 29f34b2 (post 0.1.1 pre 0.2.0)

In logcat, pairs of battery info messages arrive from the Android device (with CNL attached) .
This may or may not be important, but seems odd
```
05-21 20:56:17.726 25192-25192/info.nightscout.android I/BatteryReceived: BatteryReceived
05-21 20:56:17.767 25192-25192/info.nightscout.android I/BatteryReceived: BatteryReceived

05-21 20:56:37.708 25192-25192/info.nightscout.android I/BatteryReceived: BatteryReceived
05-21 20:56:37.752 25192-25192/info.nightscout.android I/BatteryReceived: BatteryReceived
```

**Comment by pazaan** [comment]
These are events that are triggered by Android, so there's not much we can do about the frequency at which we get them.
