### ISSUE TITLE
Add >= 12 character check for API Secret

### ISSUE THREAD

**Issue by wright-david** [pazaan/640gAndroidUploader#42]
Code version: commit 29f34b2 (post 0.1.1 pre 0.2.0)

An incorrect API_SECRET is a classic source of troubleshooting bugs. 
Worth adding a check/warning (now that it's a field on its own)

**Comment by LittleDMatt** [comment]
Also check (or force) upper case

**Comment by pazaan** [comment]
I'll also check if there's a POST that will let me check if the secret and URL are valid, before we even quit preferences.

**Comment by wright-david** [comment]
@LittleDMatt  Does it have to be upper case?

**Comment by Bal00** [comment]
Mine's not uppercase...

**Comment by wright-david** [comment]
@Bal00 Thanks!   I've seen the same confusion about uppercase before. 
Think the NS instructions mean that "API_SECRET" must be uppercase - not the user string itself.

**Comment by LittleDMatt** [comment]
From http://www.nightscout.info/wiki/labs/rest-api, but clearly (on rereading) upper case for "API_SECRET" not for the string itself :smile:
