### ISSUE TITLE
Check reported pump time against local device time

### ISSUE THREAD

**Issue by LittleDMatt** [pazaan/640gAndroidUploader#45]
Would prevent potential 'future events' recorded on NS and incorrect reporting of 'age' of SG values.
640g pump has a reputation for gaining time so some users may not be aware that their pump is several-tens of minutes ahead of actual time.

**Comment by pazaan** [comment]
Is it safe to assume the local device time is accurate?

**Comment by LittleDMatt** [comment]
Nope, but we're only using it to issue an occasional alert / message to say, 'please check your pump time is correct', so I don't think we need to cross reference local device time with some other time source.
