### ISSUE TITLE
CareLink Login ok, "Registered Devices" empty though

### ISSUE THREAD

**Issue by fbau3r** [pazaan/640gAndroidUploader#47]
#### Your Environment

* Uploader Version Number: 0.2.1
* Your Android Phone Model Name (e.g. Samsung J1 Ace): AVUS A34
* Android Version Number (e.g. use 4.4 for 4.4.4):4.4.2
* Network Connection at the time the issue occurred (Wi-Fi, Mobile): Wi-Fi

#### Brief Explanation of Issue

When Registering with Carelink, I do not get a "wrong password" error but there are no "Registered Devices" in the list neither.

#### Steps to Reproduce (for bugs)

1. Open App _NS 640g Uploader_
2. Click on Menu _Register Contour Next Link"
3. Enter my Credentials (checked them with https://carelink.minimed.eu, uploaded Data there)
4. Click on Button "Retrieve keys for USB"
5. Wait a bit
6. See screen with **Registered Devices** and a _Close_ Button
    ![screenshot_2016-05-23-08-40-02](https://cloud.githubusercontent.com/assets/1059406/15462310/349330b0-20c2-11e6-9061-f08ade45ee3b.png)

I hooked up Fiddler Proxy into my Wi-Fi connection and I could see that an SSL tunnel is created to https://carelink.minimed.eu, but I did not manage to "look inside" the Packages sent.

#### Suspicion
I suspect, that [GetHmacAndKey.doInBackground](https://github.com/pazaan/640gAndroidUploader/blob/07321c477817b9ec1459d4430b4fb8cd21cdf449/app/src/main/java/info/nightscout/android/medtronic/GetHmacAndKeyActivity.java#L239) returns [true](https://github.com/pazaan/640gAndroidUploader/blob/07321c477817b9ec1459d4430b4fb8cd21cdf449/app/src/main/java/info/nightscout/android/medtronic/GetHmacAndKeyActivity.java#L297) without setting up a new entry in the CNLConfigDbHelper somehow...? Returning _false_ in that Method would cause the `error_incorrect_password` to be shown which it does not, in my case.

**Comment by pazaan** [comment]
This has nothing to do with the networking code. This occurs when a USB stick has not yet been detected. Please quit the app, unplug and replug the USB stick. Ensure that you get a request to access the USB for the app (check the "remember" flag). Then launch the app and press "Get Now". You should get a message that you can't use the USB stick without registering it.
You should see a "Serial Number: xxxxxxx" under "Registered Devices" with a cross next to it.

**Comment by pazaan** [comment]
Subset of #39

**Comment by pazaan** [comment]
@wright-david also suggests that you can try the [OTG Troubleshooter](https://play.google.com/store/apps/details?id=com.homesoft.otgtroubshooter&hl=en) to get more info.

**Comment by fbau3r** [comment]
Totally makes sense:
> This occurs when a USB stick has not yet been detected

It has not yet been detected indeed. Furthermore, using [OTG Troubleshooter](https://play.google.com/store/apps/details?id=com.homesoft.otgtroubshooter&hl=en), tells me that my device is not capable of OTG... :cry:

Too bad, but I will not give up! Must test my other Android-Devices now... :wink:

Thank you for the quick response! This project is awesome! :+1:

**Comment by wright-david** [comment]
@fbau3r   Great issue report by the way.   Sorry to hear you are having this problem - it won't be any consolation, but I am in exactly the same situation.
@pazaan  Added this info as a FAQ

**Comment by ltomovski** [comment]
I am also having this problem .. no device registered devices

**Comment by pazaan** [comment]
I have updated 0.3.0 to do rudimentary USB OTG checks (similar to the OTG Troubleshooter). If USB OTG is not supported, a message should appear saying "It appears that this device doesn't support USB OTG". This still doesn't appear to work with the Sony Xperia, but this seems to be a "special" device ;)

Would be interested in feedback to determine if these checks are sufficient to close this issue, or we need to add some more.

**Comment by pazaan** [comment]
@ltomovski Does the OTG Troubleshooter (mentioned above), or version 0.3.0 of the app give you any more information?

**Comment by ltomovski** [comment]
Hi
the OTG Troubleshooter showed OTG is supported .. 
By the way I made it work .. but I still do not know why .. I did several restarts of the app and disconnect and reconnect the reader .. but at the end it did manage to get the serial from carelink
thanks

**Comment by pheppy** [comment]
I've noticed as well that the CNL sometimes has a problem to be recognized when connected. Reattaching the cable and/or restarting the app solves the issue. Sometimes Reattaching the OTG to the phone solves the problem, sometimes Reattaching the CNL to the OTG cable works. When many other apps are open,  cleaning out the other running apps also helps.
