### ISSUE TITLE
Problems trying to build with Android Studio (on Windows)

### ISSUE THREAD

**Issue by mattmholliday** [pazaan/640gAndroidUploader#49]
#### Your Environment

- Uploader Version Number: v0.2.1
#### Brief Explanation of Issue

Build Fails
File: Build.gradle
Line23: def process = ['sh', '-c', 'git tag -l | grep -c ".*" -'].execute().text.trim()

Results in the following error on windows: 

Gradle sync failed: CreateProcess error=2, The system cannot find the file specified

Current work around is returning 1 from gitVersion()
#### Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by wright-david** [comment]
@mattmholliday   I can build OK on Windows 10. Do you have git-scm installed?

**Comment by mattmholliday** [comment]
Yes I have git installed and have checked out https://github.com/pazaan/640gAndroidUploader.git

**Comment by pazaan** [comment]
Is it in your Windows PATH? If you open up a command prompt and run "git" is it found?

**Comment by niksimms** [comment]
I also got this. Doing a new Clone on Android studio then it would fail to compile. Same error

**Comment by wright-david** [comment]
Changing title as this is a specific problem - also created new Issue #52 about the general need for developer docs

**Comment by AnniDT1** [comment]
Also seeing same problem.
Fresh install of Win7Pro 64bit, android studio 2.1.1

**Comment by wright-david** [comment]
Windows 10, git-scm, Git's sh.exe, Cygwin's grep

I'm still getting this blowing on line 23/24
```
def gitVersion() {
    def process = ['sh', '-c', 'git tag -l | grep -c ".*" -'].execute().text.trim()
    return process.toInteger() + 1
}
```

This is despite being able to open a Git bash window and type

```
David@Samsung MINGW64 /t/Software dev/Nightscout etc/Android Studio/640gAndroidUploader (master)
$ git tag -l
v0.1.0
v0.1.1
v0.2.0
v0.2.1

David@Samsung MINGW64 /t/Software dev/Nightscout etc/Android Studio/640gAndroidUploader (master)
$ git tag -l | grep -c ".*" -
4

David@Samsung MINGW64 /t/Software dev/Nightscout etc/Android Studio/640gAndroidUploader (master)
$ sh -c git tag -l | grep -c ".*" -
42

```

**Comment by wright-david** [comment]
There are plans to look into this properly after 0.3.0 release

However in the meantime there is a 'hack' to allow Windows builds available here:
https://github.com/wright-david/640gAndroidUploader/tree/WindowsBuild

**Comment by volkerrichert** [comment]
using the latest gradle file this is solved
