### ISSUE TITLE
App crash when connected to CNL stick (without pump in range)

### ISSUE THREAD

**Issue by wright-david** [pazaan/640gAndroidUploader#5]
Code version: commit 4c42c64 (master) 
Environment: Sony D2303 (Android 5.1.1, API 22) Xperia M2

Start app, connect CNL, register USB stick (CareLink login), then sit and wait with no pump for several minutes....
... app crashes

Seen this a few times now, but nothing useful in the log file.

Obviously this might also occur if a user is having RF comms problems with the pump.

**Comment by pazaan** [comment]
I've never seen a crash when unable to connect to pump over RF. I'll see if there's a way I can repro...

**Comment by niksimms** [comment]
I've had a couple of App crashes by the system but the app did not actually crash, I suspect the USB activates the App so we get a re-launch. I have notice 2 instances of the app running at the same time, this could be a false-positive due to the amount of compiles and tests I was doing.

**Comment by wright-david** [comment]
Code version: Pre-release v0.1.0  (#2)
Environment:   Sony D2303 (Android 5.1.1, API 22)  Xperia M2

Still seeing "Unfortunately, NS 640g Uploader has stopped" [but maybe that's not an App crash] after a few minutes on real device (as above), while trying to get set up to 640G pump - on this occasion the pump should have been in range (2m line of sight, same room)

However niksimms point seems to apply to me - checking the Apps overview the app is still there, and resumes to normal main display.

**Comment by wright-david** [comment]
Code version: Pre-release v0.1.1  commit bf69577

Still getting same "Get now",  "...stopped" symptoms as I was with v0.1.0  (though the pump is now definitely out of range as the wearer has gone to bed)

**Comment by pazaan** [comment]
At one point, I changed the package from com.nightscout to info.nightscout. Is it possible you have 2 versions of the app installed that are competing for the USB detect launch activity?

**Comment by wright-david** [comment]
That was quite possible early on, but in my most recent comment it was definitely only one copy of 0.1.1 running. And was still happening after uninstall/reinstall.

**Comment by wright-david** [comment]
Code version: commit 29f34b2 (post 0.1.1 pre 0.2.0)
Environment:   Sony D2303 (Android 5.1.1, API 22)  Xperia M2

*WiFi debugging  is so great!*

Found the general area - seems to be loosing USB permissions.

Scenario 1: 
Start app, connect CNL, do nothing else...  4-5 minutes later the app stops

`
05-21 20:48:17.650 27868-28076/info.nightscout.android E/UsbManager: exception in UsbManager.openDevice
                                                                     java.lang.SecurityException: User has not given permission to device UsbDevice[mName=/dev/bus/usb/001/004,mVendorId=6777,mProductId=25104,mClass=0,mSubclass=0,mProtocol=0,mManufacturerName=Bayer HealthCare LLC,mProductName=Contour Link USB Device.....
`

See https://gist.github.com/wright-david/aca5739574a03080dc66753cd48d9154


Scenario 2: 
Connect CNL, start App, do nothing else..... app does not stop but has different errors

See https://gist.github.com/wright-david/720802acd8e48e293cbeffca68c75b7b


Afraid I haven't been able to discover anything deeper.

**Comment by wright-david** [comment]
Root cause - my Sony Xperia M2 no longer supports OTG 
(main symptom - no USB-App pairing pop-up on connection).

Unfortunately this was not obvious as I used OTG before on this phone (with the Veo uploader) - but that was before the Android OS upgrade to 5.x

**Comment by wright-david** [comment]
Useful test app:
![screenshot_2016-05-22-17-06-28](https://cloud.githubusercontent.com/assets/14233575/15517836/d99f61ac-21f1-11e6-98c4-ec2f733f6152.png)

**Comment by wright-david** [comment]
Closed somewhat prematurely, as the app should not SIGSEGV on devices that don't support USB OTG  
However there are plans to address and improve that whole area under #39

**Comment by wright-david** [comment]
Syzmon gave me a build of 0.3.0-snapshot  (I don't know which commit) and this issue was still present.

**Comment by wright-david** [comment]
Joanna on the Facebook group has just reported the same issue with "Sony Xperia U. The phone has otg..."

**Comment by wright-david** [comment]
By the way, if I run a USB OTG app on my Xperia M2 it can see the CNL
![screenshot_2016-05-31-20-13-36](https://cloud.githubusercontent.com/assets/14233575/15800892/be71c106-2a7d-11e6-87f4-d385c5d6cfec.png)

**Comment by pazaan** [comment]
Fixed in 0.3.0
