### ISSUE TITLE
Add check for USB OTG capability

### ISSUE THREAD

**Issue by wright-david** [pazaan/640gAndroidUploader#50]
Lack of device support for USB OTG is causing problems for lots of users - can we add a built-in check?

**Comment by pazaan** [comment]
Should be done as part of #39

**Comment by niksimms** [comment]
A List of OTG capable devices would be great. This should be part of the docs

**Comment by pazaan** [comment]
We already have a list of known working devices in the documentation. There's no possible way to list every OTG capable device. There are currently more than 24,000 different android variants.

**Comment by pazaan** [comment]
Added an OTG compatibility check in 0.3.0, though it still doesn't resolve the issues of false positives, such as the Sony Xperia (OTG Checker has the same problem).
