### ISSUE TITLE
Units of current SG not updated on change of preferences from mg/dL to mmol/L

### ISSUE THREAD

**Issue by wright-david** [pazaan/640gAndroidUploader#58]
* Uploader Version Number: 0.2.1
* Your Android Phone Model Name :Moto G 2nd Gen
* Android Version Number: 5.0

#### Brief Explanation of Issue
Received first SG from pump, realised it was in mg/dL, changed preferences to mmol/L, return to main screen expecting to see value displayed in mmol/L, but value was still displayed in mg/dL

1 = Mild (no impact on care)

**Comment by pazaan** [comment]
Fixed in 0.3.0
