### ISSUE TITLE
Add notification to NS if pump is suspended

### ISSUE THREAD

**Issue by glenngrimes** [pazaan/640gAndroidUploader#68]
[Enhancement]  

It would be great to know if the pump has gone into a suspended state when watching over NS, including how long for.  Our particular use case is our daughter in bed and we are monitoring through NS.  She might be hovering around the 4's (mmol) and she will possibly have been suspended, it would be nice to know/be aware of that state and how long for.

**Comment by volkerrichert** [comment]
I start to implement it. You will see it using the pump plugin "Pump 115.1U 100% normal".

But i can't find either a way to send the estimated time of being suspended to NS nor the data itself. I'll add it if available

**Comment by volkerrichert** [comment]
it seems to work

![83 5](https://cloud.githubusercontent.com/assets/640914/21296113/056caf72-c564-11e6-8aee-4af454f1663a.png)
