### ISSUE TITLE
Unable to register next meter

### ISSUE THREAD

**Issue by philipjohnmurphy** [pazaan/640gAndroidUploader#70]
#### Your Environment

- Uploader Version Number:
- Your Android Phone Model Name (e.g. Samsung J1 Ace):
- Android Version Number (e.g. use 4.4 for 4.4.4):
- Network Connection at the time the issue occurred (Wi-Fi, Mobile):
- (if relevant) Nightscout website version (e.g. 0.8.4 Funnel cake, master / dev branch):
#### Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by philipjohnmurphy** [comment]
Hi 
I am having an issue registering a new meter
I connect the new device and then am prompted to register the device.
When the username and password has been entered the visual spinning is displayed as if loading but then I am presented with the following message:
Unfortunately, NS 640g Uploader has stopped
I have tried to update the app and have tried on multiple phones and multiple next meters and I get the same error each time
Any help would be gratefully received
Phil

**Comment by philipjohnmurphy** [comment]
Have resolved by completely uninstalling the app and starting again
Talking to myself online. One of many indicators of my impending insanity. 
Just a quick note to say thank you for this development. Has made a difference to my daughters quality of life. Every little helps. 
Bring on the cure.

**Comment by pazaan** [comment]
Fixed by commit a323eb70b191510f6f954c6c252df16ed0e73acd
