### ISSUE TITLE
Cannot Register Contour Nextlink 2.4

### ISSUE THREAD

**Issue by C0DYM** [pazaan/640gAndroidUploader#75]
When I go to register a nextlink device, I fill the carelink login and password, but insists on them being incorrect. I am in america and registered first on the US carelink website, but also registered on the .eu domain incase the app pulls solely from that. Neither work and keeps saying incorrect username/password.
#### Your Environment
- Uploader Version Number: 0.4.0-Snapshot
- Your Android Phone Model Name (e.g. Samsung J1 Ace): Samsung Note 5
- Android Version Number (e.g. use 4.4 for 4.4.4): 6.0.1
- Network Connection at the time the issue occurred (Wi-Fi, Mobile): Wifi & Mobile
#### Steps to Reproduce (for bugs)

1.
2.
3.
4.

**Comment by volkerrichert** [comment]
I had the same issue. I can't remember anymore. :-( Maybe try to reduce the strength of the password.

**Comment by pazaan** [comment]
Did you do an upload of the pump to your .eu CareLink site?

**Comment by pazaan** [comment]
I've also found that if you're in the US, you'll need to set up non-US account (by saying you're not in the US), and uploading to the .eu account.

**Comment by pazaan** [comment]
Fixed by commit a323eb70b191510f6f954c6c252df16ed0e73acd
