### ISSUE TITLE
unable to compile / build

### ISSUE THREAD

**Issue by volkerrichert** [pazaan/640gAndroidUploader#77]
I try to build 640gAndroidUploader on Windows and Linux using Android Studio & grandle. I fixed a few missing things but now i got "Error:Task with name 'assembleRelease' not found in project ':app'.". If i add a task with that name i got "task with this name :app:assemleRelease already exists".... WTF?

Any hint?

**Comment by pazaan** [comment]
Are you trying to build the "app" target?

**Comment by volkerrichert** [comment]
Sure. I tried „build.gradle (Project: 640gAndroidUploader)” and build.gradle (Module: app)”

Von: Lennart Goedhart [mailto:notifications@github.com]
Gesendet: Donnerstag, 27. Oktober 2016 10:09
An: pazaan/640gAndroidUploader <640gAndroidUploader@noreply.github.com>
Cc: Volker Richert <volker.richert@addmore.de>; Author <author@noreply.github.com>
Betreff: Re: [pazaan/640gAndroidUploader] unable to compile / build (#77)


Are you trying to build the "app" target?

**Comment by volkerrichert** [comment]
I was able to build it by comment out 

release { ... }

**Comment by Pogman** [comment]
Is your windows build working? Any chance of getting a version I can run in Win 7?

**Comment by volkerrichert** [comment]
I'm using Win 10 & Linux. I had a few points with gradle running

- "def gitVersion() {....}" The bash stuff doesn't run on Windows. I just return 42 at the moment
- i have to comment out the "release {}" part. I don't know why. :-(
- you have to install the tolls version 23.0.3 in gradle file not to break others build env after send a pull request. :) The cirrent is 25.0.0 

After that, you have to at your own(!) fabric api key in the manifest

Hope that was all i did. Ask again, your wellkome

**Comment by rahim** [comment]
I'm using OSX, but I hit some these issues too - I documented and addressed a few in #82
