### ISSUE TITLE
640gAndroidUploader as a standalone Java Application on Raspberry Pi?

### ISSUE THREAD

**Issue by juzi** [pazaan/640gAndroidUploader#88]
This is just a question to the developer.
My wife has been using the 640gAndroidUploader app on an old smartphone via an OTG cable.
The phone died and we don't really have a spare one at hand at the moment. However I have plenty of raspberry PIs flying around at home.
I wonder how much work would be involved in using your code to build a standalone Java application which I could run on a Raspbian Linux. 
Any hints on how I could achieve that?
Maybe someone has done that already?

Thanks in advance!

**Comment by jotomo** [comment]
There's a python version that runs on Linux: https://github.com/pazaan/decoding-contour-next-link
That repo also has a Gitter channel where _all things 640g upload_ are discussed.
There are also some changes in a fork to upload to NS: https://github.com/tim2000s/decoding-contour-next-link/commits/master

**Comment by juzi** [comment]
thanks a lot for the links!
