### ISSUE TITLE
If "could not communicate with the 640g" then do extra poll

### ISSUE THREAD

**Issue by Tausta** [pazaan/640gAndroidUploader#95]
If "Could not communicate with the 640g. Are you near the pump?" then use polling interval 2,5 min instead of 5 min. Trying to reduce the gaps in SVG values. Because this extra poll is in the middle of the cycle when the sensor typically does not send to the pump this does not significantly increase the risk of loss communication between pump and sensor.

**Comment by volkerrichert** [comment]
implemented with 4ca906ee8f48ec46513c248f9ff3e2b2986cdc99

**Comment by Tausta** [comment]
Your Environment

    Uploader Version Number: 0.5.0-snap (latest develop)
    Your Android Phone Model Name (e.g. Samsung J1 Ace): Sony Xperia XA
    Android Version Number (e.g. use 4.4 for 4.4.4): 6.0
    Network Connection at the time the issue occurred (Wi-Fi, Mobile): WiFi
    (if relevant) Nightscout website version (e.g. 0.8.4 Funnel cake, master / dev branch): 0.9

Douple polling interval is 2 min 58 sec instead of 2 and half minute. 

\app\src\main\java\info\nightscout\android\medtronic\service\MedtronicCnlIntentService.java line 208:
MedtronicCnlAlarmManager.setAlarmAfterMillis(
                            (MainActivity.pollInterval  + MedtronicCnlIntentService.POLL_GRACE_PERIOD_MS) / (MainActivity.reducePollOnPumpAway?2L:1L)

Adding POLL_GRACE_PERIOD_MS makes 15 extra seconds and 13 seconds are time of one attempt.
Should be something like that(?):
if (MainActivity.reducePollOnPumpAway) {
  MedtronicCnlAlarmManager.setAlarmAfterMillis(MainActivity.pollInterval/2L - 13000);
} else 
 ...

![screenshot_20170114-211613](https://cloud.githubusercontent.com/assets/23084001/21957571/ce7d63c8-daa1-11e6-88b4-38154075c858.png)

**Comment by volkerrichert** [comment]
We get the last data ts. Then we add 5min (default) + 30sec. The 30 sec is not to disturb communication between pump and sensor. The half is 2:45.

If pump is away, i schedule the next poll 2:45 min from detecting pump is away, not the last poll. Maybe i should change this. And yes, it takes 13 sec to scan all frequencies.

**Comment by volkerrichert** [comment]
Change base of rescheduling to last alarm, not knowing pump is away

**Comment by volkerrichert** [comment]
can you try this version?

**Comment by Tausta** [comment]
Now the interval is 2 min 48 sec. I still think that POLL_GRACE_PERIOD_MS is too much in this situation, because POLL_GRACE_PERIOD_MS is already taken into account (when synchronized with sensor cycles). Polling interval should be as closely as possible 5 min when already synchronized with sensor cycles, now it is 5 and half.

**Comment by volkerrichert** [comment]
your right, 5 min should match best. I'll fix it later or feel free to send a PR

**Comment by volkerrichert** [comment]
i think wie can close it
