### ISSUE TITLE
insulin on board values are not matching the pump values

### ISSUE THREAD

**Issue by FionnCole12** [pazaan/640gAndroidUploader#96]
#### Your Environment

based in ireland, using mmol values just wifi on uploader (version as per instructions as of 6/01/2017) so far and a new samsung s6 uploader with bayer contour next usb. At the same time I've set up nightscout (0.9.2)for the first time and downloaded the ios app for my iphone. 

* not sure (most recent from instructions (06/1/2017)
* samsung s6
* not sure (most recent)
* WIFI
* 0.9.2
#### Brief Explanation of Issue
I'm just trying to see if I can see insulin on board values with the 640uploader/ nightscout. At the moment they seem to max out at 0.4 and also go into negative integers. In addition I don't seem to be able to get / visualise the basal regime.

#### Uploader Error Code

none showing
#### Steps to Reproduce (for bugs)

1.
2.
3.
4.
The anomoly seems to be their all the time.
#### Severity Score

1

**Comment by volkerrichert** [comment]
Can you add some photo?

And basal isn't implemented yet.

**Comment by FionnCole12** [comment]
Apology for delay in responding.  This is resolved. The insulin on board values are now showing up. I think this is because I added iob correctly on azure.

**Comment by volkerrichert** [comment]
great
